name: Django-app workflow

on: [push]
    [flake8]
    ignore =
        W503,
        F811
    exclude =
        tests/,
        */migrations/,
        venv/,
        env/
    per-file-ignores =
        */settings.py:E501
    max-complexity = 10

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        python -m flake8